name: 'CI'

on:
  push:
    branches:
      - "main"
      - "perf/gha" # for tests
  pull_request:
    branches:
      - "main"

env:
  # Use latest stable version.
  GO_VERSION: "stable"

jobs:
  test-coverage:
    name: "Test coverage"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Generate reports"
        run: cd fext && go test -race ./... -coverprofile=coverage.out -covermode=atomic
      - name: "Upload reports to Codecov"
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-different-version:
    name: "Test on different versions"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - windows-2022
          - windows-2019
        go-version:
          - "1.22"
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: "Test application"
        run: cd fext && go test -race ./...